### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by fernandobayit** [aaryanrr/DownDetector-CLI#2]
**Describe the bug**
No working with other country, ex. downdetector.com.br

**Comment by aaryanrr** [comment]
Hey @fernandogobah , thanks for reporting this. It is not possible for me to add all the domains for downdetector.com as there are too many. But the structure of the website on all those domains is same, so the tool will work. Now, after cloning the repo, you need to change the `url` variable [here](https://github.com/aaryanrr/DownDetector-CLI/blob/5feb906e8491575a63c440f5da4778280044e106/src/Scraper.py#L12) to the status page of your country specific website for downdetector.  For example, in your case you should change it to `https://downdetector.com.br/fora-do-ar` and this should work. I have also updated the tool so please update your local copy.
